INSERT INTO Pais (nome) VALUES ('Rússia'),
                               ('França'),
                               ('Portugal'),
                               ('Alemanha'),
                               ('Sérvia'),
                               ('Polônia'),
                               ('Inglaterra'),
                               ('Espanha'),
                               ('Bélgica'),
                               ('Islândia'),
                               ('Suíça'),
                               ('Croácia'),
                               ('Suécia'),
                               ('Dinamarca'),
                               ('Irã'),
                               ('Coreia do Sul'),
                               ('Japão'),
                               ('Arábia Saudita'),
                               ('Austrália'),
                               ('Tunísia'),
                               ('Nigéria'),
                               ('Marrocos'),
                               ('Senegal'),
                               ('Egito'),
                               ('México'),
                               ('Costa Rica'),
                               ('Panamá'),
                               ('Brasil'),
                               ('Uruguai'),
                               ('Argentina'),
                               ('Colômbia'),
                               ('Peru');